### ISSUE TITLE
Won't build on mac without /docs folder

### ISSUE THREAD

**Issue by hannesmcman** [StoDevX/AAO-React-Native#1013]
Hey guys, my name is Hannes and I'm new to this, but I'd like to be involved. I followed the steps from the READ-ME file, but I encounter an issue stemming from a missing /docs folder. A bunch of files are supposed to exist in this folder, which causes the build to fail. What am I missing? Thanks!

**Comment by drewvolz** [comment]
Hey @hannesmcman, thanks for reaching out. We need to update our readme because we changed the way the docs folder is generated.

In short, run `npm run bundle-data` which will traverse through all of the yaml files that are within the data directory and generate the JSON files that will appear in the docs directory.

Let us know if you run into any other issues. We'll update the readme to include that... or find a way to automate it.

**Comment by hannesmcman** [comment]
Thanks! One more question: How would I go about receiving a Google API key from one of you guys?

**Comment by hawkrives** [comment]
You can generate your own! It's a tiny bit complicated:

1. Go to https://console.developers.google.com/
2. Create a new project
3. Go to the Credentials sidebar option
4. Choose "Create credentials", then choose "API key" from the dropdown
5. Copy the key it gives you
6. Copy the `.env.sample.js` file as `.env.js`, and put the key from step 5 into the file

… I think that should work. If it doesn't, I can send you a key you can play with privately.

**Comment by hannesmcman** [comment]
Thanks! I realized the first time I did that I typed the key in wrong..after changing it I had to delete the folder, re-download it, re-enter the key and it worked!

**Comment by hawkrives** [comment]
👍👍👍👍👍

**Comment by hawkrives** [comment]
We'll keep this open until @drewvolz updates the README with the instructions about `npm run bundle-data`.

**Comment by hawkrives** [comment]
@hannesmcman Let us know if you have any other questions or issues! We'd love to help out.
