### ISSUE TITLE
Remove codepush

### ISSUE THREAD

**Issue by drewvolz** [StoDevX/AAO-React-Native#1131]
@hawkrives has a few thoughts on this:

>  - We should not change the app that people have installed. Codepush is a cool idea, but if we are going to think along these lines, we do not need to have the functionality.
> - It has become a nuisance to figure out the difference between js and binary releases
> - The iOS app store is at about a 24hr review time which is quick enough

**Comment by elijahverdoorn** [comment]
I think that removing it is a mistake. We should have a conversation about how we plan to use it, and should set some standards for notifying users that we're using it, but I think that the ability to correct our mistakes is too powerful to ignore.

**Comment by hawkrives** [comment]
On the one hand, there's a need to correct our mistakes immediately; on the other, Apple's app review is now close to 24 hours, so we'd still be able to fix bugs in ~one day.

**Comment by elijahverdoorn** [comment]
I think that because people use the app to plan their day, we have an ethical concern here - what's worse: changing an app installed on someone's device without telling them about it, or having someone rely on our app to make important decisions when that information is false? I'm really not sure.

**Comment by hawkrives** [comment]
Continuing with that train of thought, most of the "data" in the app is only sourced from the app _bundle_ in offline situations, so people checking building hours, calendar, or news will receive the latest data.

Bus schedules don't update from the network, however, but that's not a technical limitation.

**Comment by drewvolz** [comment]
@hawkrives and I absolutely agree with you @elijahverdoorn that users should be notified of any changes. But as far as the ability to correct our mistakes, we still have that ability. I feel that codepush is neat, but it's a headache.

I have a huge issue with the betas reverting back to the previous codepush bundle when I am trying to test the app. But with TestFlight, we can update beta builds easily enough, and with the Play Store, betas are able to auto-update. And with pushing updates, we are able to deliver a quality build without fearing whether we actually delivered a build. 

Back when it was taking a week for builds to be reviewed, I was pulling for codepush. But now that review times are much [more expedited](http://appreviewtimes.com/ios/distribution-chart), I am less in favor of the thing. 

Personally, I am not up to the task of implementing @hawkrives' [codepush proposal](#1044). I would be happier to take it out of the project. That being said, none of these issues are insurmountable. But they are nuisances. Frankly, I don't trust our ability to safely channel the magic that is codepush.

**Comment by hawkrives** [comment]
^ about @drewvolz's specific issue with testflight+codepush: it's not an insurmountable issue, but it's more work that needs to happen, and … there's just too much magic in codepush for my liking.

I don't trust us (read: me) to not mess up (our codepush setup / the app keys / the build process)…

(I don't want to implement my proposal, either.)

I just … I originally wanted codepush so that we could push updates without waiting for you to make the builds, @elijahverdoorn. Now that we have automated builds, and automatic beta submissions, and easily-promotable beta-to-release builds, and short Apple review times… I don't _need_ codepush anymore.

And, I've never been 100% confident in my setup _of_ codepush.

Idk. Nerves, tiredness, magic…

I just … don't want codepush anymore.

(also, in unrelated news, our builds are failing because of some codepush login shenanigans.)
