### ISSUE TITLE
Streaming events view

### ISSUE THREAD

**Issue by drewvolz** [StoDevX/AAO-React-Native#127]
It would be neat to have the feeds from [https://www.stolaf.edu/multimedia/](https://www.stolaf.edu/multimedia/) show up in the app. Luckily, there is an [RSS feed that we can make JSON](https://ajax.googleapis.com/ajax/services/feed/load?v=1.0&num=-1&q=https://www.stolaf.edu/multimedia/streams/rss/rss.cfm). Providing a list of these events which would load a view of the stream might make for a neat addition to the Streaming Media section of the app.

**Comment by hawkrives** [comment]
Ooh, that is a nice idea.

**Comment by drewvolz** [comment]
This idea now lives [here](https://github.com/StoDevX/AAO-React-Native/wiki/Streaming-events-view).

**Comment by hawkrives** [comment]
👍💯🙏

**Comment by zimmer18** [comment]
I'm thinking of a ListView that opens up into a WebView with the video. Here is an image with what I was thinking:
![img_4624](https://cloud.githubusercontent.com/assets/14142305/20289254/792097fc-aa9e-11e6-818f-e057907f3d46.JPG)

**Comment by hawkrives** [comment]
Great! Maybe include the event description and title in that webview, as well? So there's a little more substance to it than just the video.

Now for the singularly most important decision: icon picking time!

**Comment by hawkrives** [comment]
We use icons from https://cdn.rawgit.com/driftyco/ionicons/3.0/cheatsheet.html for the tabbars. 

Since this is your first entirely new view, I vote that you get to pick the icon!

Icons are never final, except when they are… like when my placeholder "smiley face" icon shipped for the Oleville calendar. So don't worry _too_ much about picking just the right one. 

I usually spam Drew with screenshots of about fifteen icons before we figure out what we want.

**Comment by zimmer18** [comment]
I was thinking about doing something similar as the Campus Dictionary. Does this picture make more sense?
![img_4626](https://cloud.githubusercontent.com/assets/14142305/20291656/58231c0a-aaad-11e6-9f22-6106467b53ca.JPG)

**Comment by hawkrives** [comment]
Yeah! That's pretty much exactly what I was thinking. Any particular reason not to include the video on the detail page? Or is it included in your mockup and I'm just misinterpreting it?

**Comment by zimmer18** [comment]
No it's not included on the detail page. I was thinking that we would have to link to the web page with the video, but we can just embed the video, right?

Also, how does the ion-ios-film icon sound?

**Comment by hawkrives** [comment]
Do we use that icon anywhere else in the app? I've thus far managed not to reuse any, I think.

**Comment by hawkrives** [comment]
We should be able to just embed the video, yeah.

**Comment by hawkrives** [comment]
You might glance at the Webcam views. As hideous as they are, they're using the same backend as the streaming events stuff. 

And thus any improvements we figure out for them, we can include in this view in the future too.

**Comment by zimmer18** [comment]
No I couldn't find the icon anywhere else on the app. I'll look at how we do the Webcam views and see if there's any improvements that could be made to both.

**Comment by zimmer18** [comment]
Working in branch [`streaming-events`](https://github.com/StoDevX/AAO-React-Native/tree/streaming-events)

**Comment by drewvolz** [comment]
@zimmer18 I think I debugged the `cloneWithRows` issue that prevented the view from loading the data. I pushed a fix and added a test `<Text>` element to display the event titles.

~~@hawkrives and myself would encourage you to construct a similar event view thing to use in streaming media. It can use the `EventView` as the foundation, but it would benefit in terms of flexibility by having its own component.~~

Scratch that last message. Please do use the `EventView` component. It could benefit from your changes -- including the disclosure indicator `>` as an action item on each row. This is a good use of this component -- sorry.

**Comment by drewvolz** [comment]
Updated the last message, which won't send a notification. Commenting here to make that happen.

**Comment by hawkrives** [comment]
Expounding a little: I think the the EventView is a perfect fit for any lists thy need to make a calendar-like view, such as Calendar or StreamingEvents. 

However, since it's currently living in the `calendar/` folder, I'd like to move it to `components/` and give it a more applicable name, like `EventListItem`. 

Given that the StreamingMedia view needs to be able to push a new view onto the stack, so actually show the event details, the generic component should also accept an `onPress` event that returns the item which was tapped. We can then use that to push a details view onto the stack. 

I'd also like it to take some prop to dictate the showing/hiding of the disclosure arrow? Since Calendar has nothing to show if you tap it, but StreamingEvents does. 

Hopefully that made sense.

**Comment by zimmer18** [comment]
@hawkrives I like you idea! Do you want to do this or do you want me to?

**Comment by hawkrives** [comment]
I'd love for you to take a stab at it!
