### ISSUE TITLE
Show app analytics in-app somewhere

### ISSUE THREAD

**Issue by hawkrives** [StoDevX/AAO-React-Native#1322]
It'd be really cool. 

I also don't entirely know if it's possible with stock GA, but it'd be really cool. 

I'm going to close this for Drew, but we can discuss while it's closed and reopen it when someone starts working on it.

**Comment by elijahverdoorn** [comment]
I think that there are potential privacy issues with this. Most users have a reasonable expectation that data about them is being collected, which I'm not taking issue with, rather I think that as a user I'd be a little off-put if that same data were handed out without permission. If we get user permission, I'm fine with some general data going out, but otherwise I'm against this idea. 

Other than it being cool (it would be) what could a user gain from knowing this information? Anything? Or are we thinking a "Stats for Nerds" screen hidden away somewhere?

**Comment by hawkrives** [comment]
I was actually thinking that it would go the other way - i've been seeing this as compensation for us having google analytics track them  

I will admit that i've been thinking that it would be prettt limited; no real-time information, for instance, and … ok, I guess I haven't thought past just showing essentially the "users over time" graph?

**Comment by elijahverdoorn** [comment]
It's a good thought. I'll keep it in mind and report back if I come up with something that this could be used for.
