### ISSUE TITLE
Landscape home screen edit needs work

### ISSUE THREAD

**Issue by drewvolz** [StoDevX/AAO-React-Native#1386]
Need to adjust width of the view after each rotation

![edit-home-landscape](https://user-images.githubusercontent.com/5240843/29050785-47edad98-7bac-11e7-9cfe-d89205473210.jpg)

**Comment by hawkrives** [comment]
This issue also shows up on iPad: not on rotate, but when you open the app in split view or slide over. It also affect the home screen on iPad. 

 
I believe the root cause is our checking of the viewport width once and caching it. I think that we will need to move that viewport check into the render function and provide the width of items as a dynamic style prop.

**Comment by hawkrives** [comment]
I'm going to try to solve this by using flexbox to make RN's layout system apply the width the the list items; that way the layout happens independently of the render calls, and I don't have to get the window size at all.
