### ISSUE TITLE
Document release process in CONTRIBUTING?

### ISSUE THREAD

**Issue by rye** [StoDevX/AAO-React-Native#1556]
Currently, I don't think the release process is documented—to my understanding, @hawkrives is the one who does this the most.  I've sat through the release process (which seems as simple as bumping the version and making a new GH release) but I'm curious if we can quantify it in the CONTRIBUTING file.

I'd like to collect as much information as possible in this issue so that I can document the general outline of how releases get done in the CONTRIBUTING file. (i.e. if a branch gets created to append to a changelog and bump a version or not, if there's a specific person who has the keys, that kind of thing)  That way, an outsider (like myself, to be honest) can sit down and read through and understand the flow of the development cycle.  This would also give a good checklist for release time and could provide a bit more rigidity to any existing practices by clearly outlining the acceptance criteria for releases.

To that end, there's also some room here for a couple of suggestions:
- Adopting something like a weekly beta schedule. (Which is something I've been told is within the realm of possibility.)  This schedule wouldn't necessarily be strictly enforced but would be more of a general guideline to follow; betas seem to be created whenever at this point, and switching to a more frequent release schedule would offer more granular data about the lifecycle and stability of new features as they get developed.  It'd basically involve just cutting a release from `master` every week or so.
- We could also consider doing milestones for each release (not just v2.4 or v2.5, but v2.4.0 or v2.4.1-beta10 or something of the like) with scheduled completion dates.  Issues and PR's would then get dumped into the appropriate place and as soon as the milestone reaches its completion date and is at 100% completion, the release could get released.  After that, the milestone could get closed and a new one could be created.  This would also be a good place to store and work on release notes.

Anyways, I'm curious to hear/get information on (i) what the existing release process is, and (ii) if there are any ideas to improve it. (including feedback on my ideas mentioned above)

Pinging @hawkrives and @drewvolz for any feedback or info you can provide.  I'll gladly pick this up and work on it in a PR.

**Comment by hawkrives** [comment]
1. The current release process is as follows:
  - Update the version in `package.json`
  - Add a new tag to a commit
  - Push the new tag to GitHub

You can accomplish the first two steps with the command `npm version v2.4.0-beta.12` if at a computer (it makes a tag for you), or you can commit the new version on GitHub and then create a "release" pointing to that commit. 

Don't forget to `git push --follow-tags` to push the new tag to GitHub, if you're working locally.

Open questions: 
- I'm not sure what happens if you tag a commit on a branch and then merge it – will Travis build the commit on the branch before it's merged? I believe it will.
- With the new restrictions on pushing directly to `master`, I think we'll have to do the tagging in two steps no matter what – I think I can disable npm's automatic tagging via the `.npmrc`, so then we'll just have to make a PR for the version bump, then either pull + tag + push or make a release though GitHub.

Edit: yes, I can disable it.

```ini
git-tag-version=false
```

**Comment by hawkrives** [comment]
I would like to say, "let's make a beta every week", without adding milestones for it – what happens in a beta, will happen in the beta, and if they're weekly then we don't need to make a judgement call about "is this big enough to make a new beta"; we'll just make one.

By having the train of betas, I think it'll result in mostly smaller betas, which is a good thing, and it'll drive us to keep `master` in a slightly more usable state. It's already pretty usable; @drewvolz  and I use the nightly builds, which are generated from `master` every night around 1am CST.

**Comment by hawkrives** [comment]
Whenever a new version is tagged, it should have release notes added.

I like to start the GitHub notes with a "compare" link, to make it easy to see _all_ the changes since the last thing we released.

- A new alpha or beta should have the changes since the last release, alpha, or beta, whichever is most recent
- A new release should have the changes since the last release

I like to make changelogs for the betas, because that makes it easier to look over and see what we've changed since the last full release.

The beta changelogs have more technical detail; I try to keep it to changes that the user/tester might notice. I only include dependency updates when they include user-facing changes, or if it's, say, a React Native upgrade. Or if I changed the Android compilation target or something.

The release changelogs are marketing information, and don't have very much technical detail at all. Features, bugs fixed, and such; never something like "updated React Native", because the user doesn't need to know that we even use RN.

**Comment by hawkrives** [comment]
Um. Miscellany: 

- I think there's something on Travis that I'll have to refresh roughly once a month? `FASTLANE_SESSION`? Once it expires, I just set up a new apple ID that doesn't have 2fa enabled, so I'll switch over to that. We'll know when it expires because the nightly process will start failing on iOS.
- The iOS and Android release processes are powered by [Fastlane](https://fastlane.tools), which is a great thing. It's configured in the `fastlane/` top-level directory.
- Most of the Travis config has migrated back into the `.travis.yml` config file; the JS build process is still in its own script, because it's annoying to have giant text blocks in the YAML file.
- We have three travis builds:
  - JS: flow typechecking, eslint linting, jest unit tests, data file validation. It also builds the `gh-pages` branch, if it's building `master`.
  - Android: builds a copy of the Android app. If running from a tag or cron build, it'll release to Google Play.
  - iOS: builds a copy of the iOS app. If running from a tag or cron build, it'll release to Testflight.

**Comment by hawkrives** [comment]
For both iOS and Android, _all_ builds wind up going through Testflight / Google Play, even the final releases. We'll just "promote" the build artifacts to Release mode from their web interfaces.

Before you make an actual app release, you'll need to make sure that you have written the changelog for the release, and included it in the release notes field.

**Comment by hawkrives** [comment]
Something else misc: `bundle exec fastlane ios refresh-dsyms` will upload the new debugging files from iTunes Connect to Bugsnag, for stack traces in native code. We can't do this in the CI, because the dSYMs aren't generated for an unspecified amount of time after the build has completed processing.

**Comment by hawkrives** [comment]
`package-lock.json` _should_ be updated by Travis, but it's not, and I haven't had time to dig into why. See `greenkeeper-lock-update` for the package that should be updating it. As a workaround, I update the lockfile about once a week manually and make a PR for it.

**Comment by hawkrives** [comment]
The Google Play account that controls the Android app is controlled by SGA, through the email `sgawebmaster@stolaf.edu`. (I think.) I also have full access to this account, through my own Google account.

The iOS app is associated with my iTunes Connect account, so that SGA doesn't have to pay the annual fee. I will add the new SGA team members upon request, but I'll only add them individually, instead of adding the `sgawebmaster` account.

**Comment by hawkrives** [comment]
There. I think that's everything.

I posted these as separate comments for easier linking.

**Comment by rye** [comment]
This will go into maintainer documentation instead—this is specifically for people who have credentials to actually deploy.
