### ISSUE TITLE
News

### ISSUE THREAD

**Issue by hawkrives** [StoDevX/AAO-React-Native#16]
> This might be just pulling from APIs, reading RSS feeds, or could be as simple as webviews

**Comment by drewvolz** [comment]
Instead of parsing the XML RSS news feed [www.wp.stolaf.edu/feed](www.wp.stolaf.edu/feed), what about using Google to do the heavy-lifting? I noticed that the Calendar @elijahverdoorn implemented handles JSON very nicely. 

@hawkrives @elijahverdoorn thoughts about using Google to parse the XML into JSON? [https://ajax.googleapis.com/ajax/services/feed/load?v=1.0&num=-1&q=https://wp.stolaf.edu/feed/](https://ajax.googleapis.com/ajax/services/feed/load?v=1.0&num=-1&q=https://wp.stolaf.edu/feed/)

**Comment by elijahverdoorn** [comment]
I'd love to avoid doing anything in XML - JSON works so much better with JS. This seems like a great idea.

**Comment by hawkrives** [comment]
I guess it wouldn't be any more work to transition away from something like that to XML parsing if google decides to sunset that tool later. Sure, why not.

**Comment by hawkrives** [comment]
![image](https://cloud.githubusercontent.com/assets/464441/17722609/66881488-646e-11e6-80ff-7c829f9fc1c6.png)

<img width="487" alt="screen shot 2016-08-17 at 11 33 33 am" src="https://cloud.githubusercontent.com/assets/464441/17722616/718cf6e6-646e-11e6-8163-c4b2e490c805.png">

Current state
