### ISSUE TITLE
Fix rotate on android edit home

### ISSUE THREAD

**Issue by drewvolz** [StoDevX/AAO-React-Native#1601]
Finish up the very last issue that #1474 tackled.

Starting Android in portrait and rotating to landscape in "Edit Home".

![android-after](https://user-images.githubusercontent.com/5240843/30467161-cbaee04e-99b0-11e7-9eac-9c730aed6fca.png)

**Comment by hawkrives** [comment]
thx

**Comment by hawkrives** [comment]
I think this is a React Native bug.

- It only happens if you _start_ in Portrait, then rotate to landscape; if you start in landscape, you can't trigger this, no matter how many times you rotate
- The view hierarchy has the correct widths for the rows

![screenshot_1505619716](https://user-images.githubusercontent.com/464441/30517806-43f05288-9b30-11e7-910b-9e7ec1459560.png)

As such, I'm going to take this out of the queue for 2.4. We'll revisit it when we next upgrade React Native.

**Comment by rye** [comment]
Seems like this is no longer the case on 2.5.0 β2.  (If this was an RN bug, it's fixed in the latest.)

**Comment by hawkrives** [comment]
woot.
