### ISSUE TITLE
Add a prop to NewsList to force opening news articles in SFViewController/CustomTabs

### ISSUE THREAD

**Issue by hawkrives** [StoDevX/AAO-React-Native#1604]
Needed for https://github.com/carls-app/carls/issues/68, because Carleton's RSS feeds are truncated.

**Comment by hawkrives** [comment]
I've come around on this… what do you all think about always opening the site in a browser, and just forgoing the embedded RSS views entirely?

It'd fix https://github.com/StoDevX/AAO-React-Native/issues/1909, for one.

/cc @StoDevX/all-about-olaf

**Comment by drewvolz** [comment]
Mixed feelings.

I judge apps that don't have native views for these things. Because we have the data and we should be responsible for rendering it because we fetched it already.

Are we writing off things that are issues by eliminating features we've developed? Not to say that I'm trying to hold onto a mistake because we've spent a lot of time making it. But I'm not sure if we're excusing _not_ fixing it and turning the app more into a web app, or if it's right to present a website.

And to be less difficult, I could be bribed if we enable Reader mode by default for news articles in Safari.

**Comment by hawkrives** [comment]
Except we don't always have the data. 

And when we do, there are lots of edge cases - Videos, iframes, audio. Pdf embeds. Web views not respecting the screen width of the device.

I've just switched to thinking that _not_ doing our own thing is superior. I used to think the other way.

**Comment by hawkrives** [comment]
I guess I don't have a reason to not enable reader mode by default, except that it's inconsistent if you open a page that safari doesn't detect an article on (it won't enable reader mode then.)

Also I tend to force reader mode on for reader-hostile sites, which I don't think we have any of here (except maybe Oleville, since it's not responsive.)
