### ISSUE TITLE
Create a Menu Item detail screen

### ISSUE THREAD

**Issue by hawkrives** [StoDevX/AAO-React-Native#1609]
Bigger title, the description, and the _nutritional information_ (and the dietary icons with labels, ofc.)

BonApp's API gives us back nutritional information:

https://github.com/StoDevX/AAO-React-Native/blob/3aaa0016509c8a195d5d28ef4080b3db4d823694/source/views/menus/types.js#L22-L28

**Comment by hawkrives** [comment]
I should note that I don't remember how many items actually have that info, but surely some do?

**Comment by drewvolz** [comment]
I think the nutrition type you've linked to is the tip of the iceberg. For example:

`macaroni whole grain cooked` is an item on Stav's menu under pasta. We can query its `id` to find more detailed info

http://legacy.cafebonappetit.com/api/2/items?item=5290840

<details>
<summary>Want to ruin the surprise?</summary>

5290840  |  
-- | --
id | "5290840"
label | "macaroni whole grain cooked"
description | ""
zero_entree | "0"
cor_icon | Object
price | ""
sizes | 

nutrition_summary  |  
-- | --
kcal | 170
well_being | ""
well_being_image | ""

**nutrition_details**

calories  |  
-- | --
calories |  
label | "Calories"
value | "170"
unit | ""

servingSize  |  
-- | --
label | "Serving Size"
value | "4.0"
unit | "oz"

fatContent  |  
-- | --
label | "Total Fat"
value | "15"
unit | "g"

saturatedFatContent  |  
-- | --
label | "Saturated Fat"
value | "0"
unit | "g"

transFatContent  |  
-- | --
label | "Trans Fat"
value | "0"
unit | "g"

cholesterolContent |  
label | "Cholesterol"
value | "0"
unit | "mg"
sodiumContent |  
label | "Sodium"
value | "5"
unit | "mg"
carbohydrateContent |  
label | "Total Carbohydrate"
value | "35"
unit | "g"
fiberContent |  
label | "Dietary Fiber"
value | "4"
unit | "g"
sugarContent |  
label | "Sugars"
value | "0"
unit | "g"
proteinContent |  
label | "Protein"
value | "7"
unit | "g"
ingredients | ""
ingredient_details | ""
nutrition_info | "            <div class='menu-item-nutrition'>\n                <h4 class='food-item-name'>Nutrition Information:</h4>\n                    <h4 class='food-item-name modal-title'>macaroni whole grain cooked</h4>\n        <div style='font-weight: bold;' class='menu-item-serving-size' data-portion='4.0'><span>Serving Size:</span> 4.0 oz.</div>\n        <table class='eni-menu-facts' onselectstart='return false;' onmousedown='return false;' oncopy='return false;'>\n                \n                <tr>\n                                            <td class='fdaSection-0'>Calories</td>\n                <td>170</td>\n            \n                                            <td class='eni-facts-column2 fdaSection-0'>Sodium</td>\n                <td>5mg</td>\n            \n        </tr>\n                <tr>\n                                            <td class='fdaSection-0'>Total Fat</td>\n                <td>1.5g</td>\n            \n                                            <td class='eni-facts-column2 fdaSection-0'>Total Carbohydrate</td>\n                <td>35g</td>\n            \n        </tr>\n                <tr>\n                                            <td class='fdaSection-1'>Saturated Fat</td>\n                <td>0g</td>\n            \n                                            <td class='eni-facts-column2 fdaSection-1'>Dietary Fiber</td>\n                <td>4g</td>\n            \n        </tr>\n                <tr>\n                                            <td class='fdaSection-1'>Trans Fat</td>\n                <td>0g</td>\n            \n                                            <td class='eni-facts-column2 fdaSection-1'>Sugars</td>\n                <td>0g</td>\n            \n        </tr>\n                <tr>\n                                            <td class='fdaSection-0'>Cholesterol</td>\n                <td>0mg</td>\n            \n                                            <td class='eni-facts-column2 fdaSection-0'>Protein</td>\n                <td>7g</td>\n            \n        </tr>\n            </table>\n<div class='disclaimer'>\n    <p><span class='asterisk'>*</span> We attempt to provide nutrition information that is as complete as possible. The nutritional values are based on standard product formulations, data from our suppliers, and are based on the specified portion size. Variations may occur due to the use of regional suppliers, seasonal influences, differences in product preparation at the unit level, and recipe revisions. Nutrient values are rounded according to FDA Rounding Rules. For your convenience at self-serve station, we have provided utensils that will help you approximate the specified portion.</p>\n</div>                    <div class='disclaimer'>\n                <p><span class='asterisk'>*</span> We attempt to provide nutrition information that is as complete as possible. The nutritional values are based on standard product formulations, data from our suppliers, and are based on the specified portion size. Variations may occur due to the use of regional suppliers, seasonal influences, differences in product preparation at the unit level, and recipe revisions. Nutrient values are rounded according to FDA Rounding Rules. For your convenience at self-serve station, we have provided utensils that will help you approximate the specified portion.</p>\n            </div>"
special | 0
rating | ""
connector | ""
options |  
vendors |  
monotony |  
cor_icons |  
4 |  
label | "Vegan"
description | "Vegan: Contains absolutely no animal or dairy products."
image | "http://legacy.cafebonappetit.com/assets/cor_icons/menu-item-type-668e3c.png?v=1470070467"
is_filter | "Y"
allergen | 0
vendors |  
reviews |  


```

**Comment by drewvolz** [comment]
`macaroni whole grain cooked`, or `5290840` is an item we can query to find more detailed info

http://legacy.cafebonappetit.com/api/2/items?item=5290840

<details>
<summary>Expand to see all of the nutrition info</summary>

5290840  |  
-- | --
id | "5290840"
label | "macaroni whole grain cooked"
description | ""
zero_entree | "0"
cor_icon | Object
price | ""
sizes | 

nutrition_summary  |  
-- | --
kcal | 170
well_being | ""
well_being_image | ""

**nutrition_details**

calories  |  
-- | --
calories |  
label | "Calories"
value | "170"
unit | ""

servingSize  |  
-- | --
label | "Serving Size"
value | "4.0"
unit | "oz"

fatContent  |  
-- | --
label | "Total Fat"
value | "15"
unit | "g"

saturatedFatContent  |  
-- | --
label | "Saturated Fat"
value | "0"
unit | "g"

transFatContent  |  
-- | --
label | "Trans Fat"
value | "0"
unit | "g"

cholesterolContent  |  
-- | --
label | "Cholesterol"
value | "0"
unit | "mg"

sodiumContent  |  
-- | --
label | "Sodium"
value | "5"
unit | "mg"

carbohydrateContent  |  
-- | --
label | "Total Carbohydrate"
value | "35"
unit | "g"

fiberContent  |  
-- | --
label | "Dietary Fiber"
value | "4"
unit | "g"

sugarContent  |  
-- | --
label | "Sugars"
value | "0"
unit | "g"

proteinContent  |  
-- | --
label | "Protein"
value | "7"
unit | "g"

ingredients  |  
-- | --
ingredient_details | ""
nutrition_info | <div class='menu-item-nutrition'><h4 class='food-item-name'>Nutrition Information:</h4>    <h4 class='food-item-name modal-title'>macaroni whole grain cooked</h4><div style='font-weight: bold;' class='menu-item-serving-size' data-portion='4.0'><span>Serving Size:</span> 4.0 oz.</div><table class='eni-menu-facts' onselectstart='return false;' onmousedown='return false;' oncopy='return false;'><tr> <td class='fdaSection-0'>Calories</td><td>170</td>  <td class='eni-facts-column2 fdaSection-0'>Sodium</td><td>5mg</td>   </tr><tr> <td class='fdaSection-0'>Total Fat</td><td>1.5g</td>  <td class='eni-facts-column2 fdaSection-0'>Total Carbohydrate</td><td>35g</td>   </tr><tr> <td class='fdaSection-1'>Saturated Fat</td><td>0g</td>  <td class='eni-facts-column2 fdaSection-1'>Dietary Fiber</td><td>4g</td>   </tr><tr> <td class='fdaSection-1'>Trans Fat</td><td>0g</td>  <td class='eni-facts-column2 fdaSection-1'>Sugars</td><td>0g</td>   </tr><tr> <td class='fdaSection-0'>Cholesterol</td><td>0mg</td>  <td class='eni-facts-column2 fdaSection-0'>Protein</td><td>7g</td>   </tr>    </table><div class='disclaimer'>   <p><span class='asterisk'>*</span> We attempt to provide nutrition information that is as complete as possible. The nutritional values are based on standard product formulations, data from our suppliers, and are based on the specified portion size. Variations may occur due to the use of regional suppliers, seasonal influences, differences in product preparation at the unit level, and recipe revisions. Nutrient values are rounded according to FDA Rounding Rules. For your convenience at self-serve station, we have provided utensils that will help you approximate the specified portion.</p></div><div class='disclaimer'><p><span class='asterisk'>*</span> We attempt to provide nutrition information that is as complete as possible. The nutritional values are based on standard product formulations, data from our suppliers, and are based on the specified portion size. Variations may occur due to the use of regional suppliers, seasonal influences, differences in product preparation at the unit level, and recipe revisions. Nutrient values are rounded according to FDA Rounding Rules. For your convenience at self-serve station, we have provided utensils that will help you approximate the specified portion.</p>
special | 0
rating | ""
connector | ""
options |  
vendors |  
monotony | 

cor_icons  |  
-- | --
4 |  
label | "Vegan"
description | "Vegan: Contains absolutely no animal or dairy products."
image | "http://legacy.cafebonappetit.com/assets/cor_icons/menu-item-type-668e3c.png?v=1470070467"
is_filter | "Y"
allergen | 0
vendors |  
reviews |
</details>

**Comment by hawkrives** [comment]
<details><summary>As json</summary>


```json
﻿﻿{
  "items": {
    "5290840": {
      "id": "5290840",
      "label": "macaroni whole grain cooked",
      "description": "",
      "zero_entree": "0",
      "cor_icon": {
        "4": "Vegan"
      },
      "price": "",
      "sizes": [],
      "nutrition_summary": {
        "kcal": 170,
        "well_being": "",
        "well_being_image": ""
      },
      "nutrition_details": {
        "calories": {
          "label": "Calories",
          "value": "170",
          "unit": ""
        },
        "servingSize": {
          "label": "Serving Size",
          "value": "4.0",
          "unit": "oz"
        },
        "fatContent": {
          "label": "Total Fat",
          "value": "15",
          "unit": "g"
        },
        "saturatedFatContent": {
          "label": "Saturated Fat",
          "value": "0",
          "unit": "g"
        },
        "transFatContent": {
          "label": "Trans Fat",
          "value": "0",
          "unit": "g"
        },
        "cholesterolContent": {
          "label": "Cholesterol",
          "value": "0",
          "unit": "mg"
        },
        "sodiumContent": {
          "label": "Sodium",
          "value": "5",
          "unit": "mg"
        },
        "carbohydrateContent": {
          "label": "Total Carbohydrate",
          "value": "35",
          "unit": "g"
        },
        "fiberContent": {
          "label": "Dietary Fiber",
          "value": "4",
          "unit": "g"
        },
        "sugarContent": {
          "label": "Sugars",
          "value": "0",
          "unit": "g"
        },
        "proteinContent": {
          "label": "Protein",
          "value": "7",
          "unit": "g"
        }
      },
      "ingredients": "",
      "ingredient_details": "",
      "nutrition_info": "            <div class='menu-item-nutrition'>\n                <h4 class='food-item-name'>Nutrition Information:</h4>\n                    <h4 class='food-item-name modal-title'>macaroni whole grain cooked</h4>\n        <div style='font-weight: bold;' class='menu-item-serving-size' data-portion='4.0'><span>Serving Size:</span> 4.0 oz.</div>\n        <table class='eni-menu-facts' onselectstart='return false;' onmousedown='return false;' oncopy='return false;'>\n                \n                <tr>\n                                            <td class='fdaSection-0'>Calories</td>\n                <td>170</td>\n            \n                                            <td class='eni-facts-column2 fdaSection-0'>Sodium</td>\n                <td>5mg</td>\n            \n        </tr>\n                <tr>\n                                            <td class='fdaSection-0'>Total Fat</td>\n                <td>1.5g</td>\n            \n                                            <td class='eni-facts-column2 fdaSection-0'>Total Carbohydrate</td>\n                <td>35g</td>\n            \n        </tr>\n                <tr>\n                                            <td class='fdaSection-1'>Saturated Fat</td>\n                <td>0g</td>\n            \n                                            <td class='eni-facts-column2 fdaSection-1'>Dietary Fiber</td>\n                <td>4g</td>\n            \n        </tr>\n                <tr>\n                                            <td class='fdaSection-1'>Trans Fat</td>\n                <td>0g</td>\n            \n                                            <td class='eni-facts-column2 fdaSection-1'>Sugars</td>\n                <td>0g</td>\n            \n        </tr>\n                <tr>\n                                            <td class='fdaSection-0'>Cholesterol</td>\n                <td>0mg</td>\n            \n                                            <td class='eni-facts-column2 fdaSection-0'>Protein</td>\n                <td>7g</td>\n            \n        </tr>\n            </table>\n<div class='disclaimer'>\n    <p><span class='asterisk'>*</span> We attempt to provide nutrition information that is as complete as possible. The nutritional values are based on standard product formulations, data from our suppliers, and are based on the specified portion size. Variations may occur due to the use of regional suppliers, seasonal influences, differences in product preparation at the unit level, and recipe revisions. Nutrient values are rounded according to FDA Rounding Rules. For your convenience at self-serve station, we have provided utensils that will help you approximate the specified portion.</p>\n</div>                    <div class='disclaimer'>\n                <p><span class='asterisk'>*</span> We attempt to provide nutrition information that is as complete as possible. The nutritional values are based on standard product formulations, data from our suppliers, and are based on the specified portion size. Variations may occur due to the use of regional suppliers, seasonal influences, differences in product preparation at the unit level, and recipe revisions. Nutrient values are rounded according to FDA Rounding Rules. For your convenience at self-serve station, we have provided utensils that will help you approximate the specified portion.</p>\n            </div>",
      "special": 0,
      "rating": "",
      "connector": "",
      "options": [],
      "vendors": [],
      "monotony": {}
    }
  },
  "cor_icons": {
    "4": {
      "label": "Vegan",
      "description": "Vegan: Contains absolutely no animal or dairy products.",
      "image": "http://legacy.cafebonappetit.com/assets/cor_icons/menu-item-type-668e3c.png?v=1470070467",
      "is_filter": "Y",
      "allergen": 0
    }
  },
  "vendors": {},
  "reviews": {}
}
```

</details>

**Comment by hannesmcman** [comment]
Whoah how many of them have the ingredients listed? As someone who is allergic to dairy,  that would be a game changer...

**Comment by hawkrives** [comment]
… some of them? I don't know offhand

**Comment by hawkrives** [comment]
`curl 'http://legacy.cafebonappetit.com/api/2/menus?cafe=261'` will get you the list of menu items; you can pass individual item IDs to `http://legacy.cafebonappetit.com/api/2/items?item=` to see the full nutrition info.
