### ISSUE TITLE
Release Train Idea: one release per break

### ISSUE THREAD

**Issue by hawkrives** [StoDevX/AAO-React-Native#1642]
Release at the end of:
- Summer break
- Fall break
- Thanksgiving
- Christmas
- Interim
- Spring

Advantages:
- students get back on campus and get a new version of the app
- advantages of release trains (predictable releases for new features, etc)

Disadvantages:
- ???

Thoughts (on trains in general, or on this specific proposal)?

**Comment by rye** [comment]
I like this idea, and here are some comments/additional ideas:

My only concern is that some breaks are closer together than others.  So, not many new features would fit nicely between Thanksgiving and Christmas.  It's still possible, but could get hairy.  (The Christmas release might just be a small one, too, that's fine.)

This train scheme would generally be nice because it also gives developers the opportunity to work during the break to make sure that the release is ready to drop when people return.

There's the possibility of folding this into #1556, too.  @hawkrives, I think, had mentioned weekly betas as an option, and I think this is an excellent model to adhere to as well.  Effectively, the following scheme might come from this:

- MINOR version bumps would occur at the end of each break.
- PATCH version bumps would occur as issues get discovered in userland
  - In order to keep features separate from fixes, we could create a branch off of the released tag and use that to add fixes to broken versions, and thus to perform patch bumps.
    - This way, users do not get new features that are still in development.
    - These hotfix branches could get merged into master to fix the betas and nightlies as well.
- Beta releases could then happen every week, if nothing but to include dependency updates.
  - Betas would include the latest hotfixes from the aforementioned branches and would also include feature development.

So a developer making a hotfix would branch from the latest release and work on that, then create a release on the branch before merging their fixes back into master.  The patch releases are just a chain of fixes after the most recent minor version, but feature development goes into master until the next minor bump and so master grows ahead of the hotfixes.

I'd be interested in exploring the advantages and disadvantages of this kind of flow.

**Comment by hawkrives** [comment]
I think this can be closed; we managed to get a new release out after Fall Break, and this issue remaining open isn't going to get one out after Thanksgiving by itself.
