### ISSUE TITLE
Cage Menu

### ISSUE THREAD

**Issue by hawkrives** [StoDevX/AAO-React-Native#20]
@elijahverdoorn, IIRC the problem with the Cage menu it that it's never updated. Essentially ever.

**Comment by elijahverdoorn** [comment]
@hawkrives Yeah, I think that the best move is to just do it manually. I'm going to get a list from Randy Clay, then just put that into JSON. My development team will manage updating that JSON file manually (unless we can find something better). Since it rarely updates, I don't anticipate much work here.

**Comment by hawkrives** [comment]
… can I request that you please put the json file on github somewhere? I know there were many times that I've wanted to update data in AAO in the past, especially around building hours over breaks, but couldn't because it was all hard-coded. 

and while it's great to move it to Oleville, … idk. I'm just always really nervous about things that live in Oleville. And it's harder for the wider community to participate, unless…

What do you think about integrating some sort of feedback system, so people can submit data updates from the app?

(Maybe not v1, but that sounds cool to me. @drewvolz, thoughts?)

**Comment by elijahverdoorn** [comment]
Yeah, I'm thinking that Github will be ok for the JSON files. I like the idea of fast contributing and updating. I think that having a fallover file that is stored locally so that if a user has no internet connection they can see SOMETHING. even if it is slightly outdated. We can put a disclaimer in there for if there is no internet that the data might not be totally accurate. I'm going to keep developing with the files stored locally (since it's easier) but once I prepare to ship v1 I'll change them all to fetch the JSON from GitHub.

**Comment by hawkrives** [comment]
If you put the JSON files in a folder here, and have it load them from that folder, I'll submit a PR to add the updating-ffrom-github-with-fallback behavior.

**Comment by elijahverdoorn** [comment]
All the data that I currently pull is in the /data folder, and will continue with that pattern. (unless you set a new pattern, then I can follow that.)

**Comment by hawkrives** [comment]
nope, sounds good to me!

**Comment by hawkrives** [comment]
My current plan is to use either https://rawgit.com/ or Github directly to serve the JSON files, so any change that's made to them is mirrored to the app.

**Comment by elijahverdoorn** [comment]
Got the data for this when I was on campus, so I'm building the json.

**Comment by elijahverdoorn** [comment]
PR #33

**Comment by elijahverdoorn** [comment]
This is done.
