### ISSUE TITLE
Add TES Tab to SIS View

### ISSUE THREAD

**Issue by hannesmcman** [StoDevX/AAO-React-Native#2029]
I saw that there was talk about adding a TES view, but there were worries about getting permission from IT before implementing it. I think in the meantime it would be useful to add the TES to the homescreen as a url view, similar to the moodle, campus map views. Thoughts?

**Comment by hawkrives** [comment]
I'll be blunt: I don't want to add a TES view that's not resized for phone screens. The only place we link to that's not responsive or mobile optimized is Oleville in the News section, and I'd like for them to be responsive. 

I will say that TES won't be responsive at least through the rest of this academic year, and I can't say anything about beyond that because the summer is always an unknown.

**Comment by hannesmcman** [comment]
Oh okay. That makes sense!

**Comment by hawkrives** [comment]
Actually, didn't I optimized the main entry screen for mobile last year?

If you log in, does it fit itself to your phone screen? If it does, I can just fix the login screen and we can think about adding a button again. (Although I feel like this belongs under a renamed SIS tab, almost.)
