### ISSUE TITLE
Add TouchID/Face ID for login to SIS and SIS module

### ISSUE THREAD

**Issue by hannesmcman** [StoDevX/AAO-React-Native#2124]
This would make the login process easier and add an additional layer of protection for the SIS module for those who desire it. Check out https://github.com/naoufal/react-native-touch-id

**Comment by hawkrives** [comment]
@hannesmcman While you're in SIS-land, there are several feature ideas in https://github.com/StoDevX/AAO-React-Native/issues/13 that we haven't gotten back around to (mainly course search, since that doesn't require any server-side changes; all the course data dating back to 1994-fall lives at https://github.com/stodevx/course-data/tree/gh-pages, updated once a day.)
