### ISSUE TITLE
Handle errors across the app

### ISSUE THREAD

**Issue by drewvolz** [StoDevX/AAO-React-Native#2411]
We are flying dangerously and being negligent of crashes and errors within the app. We've been crashing due to string manipulation within student orgs. If outside data is our downfall, we should change that. Short of rewriting things, the very least we can do is handle potential errors from causing a crash.

We should pay attention to error boundaries
https://reactjs.org/docs/error-boundaries.html

Or implement an exception handler of sorts
https://github.com/master-atul/react-native-exception-handler

**Comment by hawkrives** [comment]
You linked to the same link twice, FYI

**Comment by drewvolz** [comment]
Fixed

**Comment by hawkrives** [comment]
For some reason, I think that Wix's react-native-navigation … er, sandboxes each screen? I think that it's impossible for a JS exception to bring down the whole app with RNN. 

Something something because the routing / navigation is done with native code and separate "applications" are started for each screen, which is why we register them all at startup. Something something.

**Comment by drewvolz** [comment]
Closing due to... we’ll come back to this if we rehash it.
