### ISSUE TITLE
Radio streams stuck on “starting”

### ISSUE THREAD

**Issue by drewvolz** [StoDevX/AAO-React-Native#2544]
Both streams will not play.

**Comment by drewvolz** [comment]
KRLX finally resolved. Still waiting for KSTO.

**Comment by drewvolz** [comment]
~Where is KSTO's stream defined? The source looks blank to me.~

Edit: I remember now that we load the webpage in the background as to forward on analytics to streaming media.

**Comment by hawkrives** [comment]
uh. If one is fixed, so is the other. The issue is in how the WebView handles "user initiated actions" to start the audio, since you're required to interact with the element that starts the audio.

Edit: by 'required' I mean Safari and other web browsers won't play any media until the user has interacted with the page to start the audio playing. And because we're programmatically starting the audio from a different context, it gets funky.

**Comment by drewvolz** [comment]
Closing as we're tracking this in #2207
