### ISSUE TITLE
Course Search: Filter buttons lagging/causing app crash

### ISSUE THREAD

**Issue by hannesmcman** [StoDevX/AAO-React-Native#2720]
Adding filters to course search is almost impossible, with how much it is lagging. It sometimes even causes the app to crash.

**Comment by hawkrives** [comment]
I've got a branch where I was working on making a FilterView handle its own state, then passing that changed state back out when the view is dismissed, instead of making the state be handled entirely in Redux.

Theoretically, that'd ensure that we only do the heavy data work once per filter adjustment.

I don't know if it'll _solve_ this, but it should help somewhat.

**Comment by hannesmcman** [comment]
<img width="504" alt="screen shot 2018-08-02 at 7 30 00 pm" src="https://user-images.githubusercontent.com/24640726/43617851-8ce92824-968a-11e8-8794-7478c19d1185.png">

Check out the CPU usage when the "Show All" button is pressed.

Also Memory usage is ridiculous.

<img width="362" alt="screen shot 2018-08-02 at 7 31 55 pm" src="https://user-images.githubusercontent.com/24640726/43617891-c84709b8-968a-11e8-87f6-a7a99f8be6bf.png">

**Comment by hawkrives** [comment]
impressive…
