### ISSUE TITLE
[course search] Cancel button in search bar only visible when focused

### ISSUE THREAD

**Issue by hawkrives** [StoDevX/AAO-React-Native#2771]
Follow-up to #2770 

- If you hit Cancel, which isn't always available (you have to have the search box focused first), you are returned to the overview
- If you dismiss the keyboard by scrolling, the cancel buttons goes away (because you aren't focused in the search box anymore)
- ~If you clear the search query, you do not enter "browse" mode (should this be a different issue?)~ (Resolved in #2781 )

Idk.

**Comment by hannesmcman** [comment]
I think the third one could be a separate issue... especially since the absence of the cancel button when the search bar isn't focused is only an issue on iOS.

**Comment by hannesmcman** [comment]
Fixing the "cancel button not always visible" issue might have to go upstream to https://github.com/umhan35/react-native-search-bar

**Comment by hawkrives** [comment]
so stream of consciousness 

what if

- the content area is the welcome screen
- no big title (aw; saves us needing to hide it)
- if you start searching, results show up and hide the welcome content
- if no results, say so – don't show welcome content if search is active
- implement "browse" via special "match all" filter to avoid a separate mode?

thoughts? elaboration requests?

**Comment by hannesmcman** [comment]
@hawkrives Not quite sure if I can picture what you're describing...could you elaborate?

**Comment by hannesmcman** [comment]
@hawkrives Can we rename this to: "Cancel button in search bar only visible when focused"?

**Comment by hannesmcman** [comment]
I've done some digging on this..and the `showsCancelButton` prop of `react-native-search-bar` does not help us here...my guess is that there is a native prop that needs to be bridged to in order to access the functionality we want. After looking at the [docs](https://developer.apple.com/documentation/uikit/uisearchbar) for `UISearchBar`, it's not clear what this prop may be. However, it must be possible since the Apple Music app has a search bar with our desired behavior:

<img src="https://user-images.githubusercontent.com/24640726/44060965-10da1d0c-9f1c-11e8-8a94-76776c0f9524.jpeg" width=300>

**Comment by hawkrives** [comment]
Mail.app does, as well, fwiw

**Comment by hannesmcman** [comment]
Anybody got a friend at Apple?

**Comment by hannesmcman** [comment]
Not a problem anymore, thanks to #2790.
