### ISSUE TITLE
Course Search: ScrollToLocation causes exception if SectionList is empty

### ISSUE THREAD

**Issue by hannesmcman** [StoDevX/AAO-React-Native#2849]
Within Course Search, ScrollToLocation is called when a new query is made, or when the search bar is cleared. In both of these cases, if the course results list is empty we get the following exception:

<img width="308" alt="screen shot 2018-08-21 at 3 52 02 pm" src="https://user-images.githubusercontent.com/24640726/44428624-86159080-a55a-11e8-991f-f71c2f6c31ca.png">

This will cause the app to crash so it is critical that we get to the bottom of this

**Comment by hannesmcman** [comment]
I mean we could just put it in a try-catch block and do nothing if it throws an error...but that's probably not best practice

**Comment by hawkrives** [comment]
Can't we just check to see if the number of results is >= 1?

**Comment by hannesmcman** [comment]
nah since we don't have access to the results list in the component which is calling `scrollToLocation` (CourseSearchResultsView). Is there a way to pass this info up from a child to a parent?

**Comment by hawkrives** [comment]
We should expose an instance method on CourseSearchResultsList and call that, instead of passing the ref up, so that the internal method can check for the size of the list before scrolling. 

Essentially we need to get a ref of the CourseResultsList itself, rather than the SectionList within in; to do so, change the getRef on Results to just a ref={}, and then you can just call any methods that we define on the class (like renderItem or onPressRow). So then we'd just define a scrollToTop method on ResultsList, which we could call from the same place in the Search interface, and it would check internally if there are any items and only scroll if there are. 

Does that make sense?

**Comment by hannesmcman** [comment]
@hawkrives That makes sense, but we'd have to move the search function out of the render() of CourseResultsList and move the results to state to be able to access that right?

**Comment by hawkrives** [comment]
I don't _think_ so…

I can do a PR today so show you what I mean (or prove myself wrong, we'll see)
