### ISSUE TITLE
Disable Greenkeeper?

### ISSUE THREAD

**Issue by hawkrives** [StoDevX/AAO-React-Native#2937]
Impetus: Greenkeeper doesn't understand Yarn workspaces.

```
$ greenkeeper-lockfile-update
Error: Command failed: yarn add 'react-native-popover-view@1.0.8'
error Running this command will add the dependency to the workspace root rather than the workspace itself, which might not be what you want - if you really meant it, make it explicit by running this command again with the -W flag (or --ignore-workspace-root-check).
```

There may be a way to configure Greenkeeper to accept that; there may not. I don't particularly care to investigate anymore; I think I've reached my breaking point.

To add to that, ESLint is currently at 5.5.0 – we're at 5.0.1, and I haven't seen an ESLint update PR in a while. `react-native-onesignal` is at 3.2.6, and we're at 3.1.4. `react-native-device-info` is 0.22.5; we're 0.22.4 (although that one may be on me).

So we're missing some updates, too, is what I'm saying.

Plus, it's always been a pitch-black box to us, as to how to fix it when it breaks, and it's one of the two things left running on Travis because I just never mustered the will to port it to CircleCI.

---

I propose that we disable Greenkeeper, and replace it by manually running `yarn outdated` on a weekly basis – we could even set up an automated thing on CI or our server to send us an issue / email if there are updates.

or we wind up building our own greenkeeper, which shouldn't<sup>[citation needed]</sup> be terribly complicated, especially if we run it on a schedule instead of attempting to do it live. (IE, run `yarn outdated --json`, pipe it to a script, then run `yarn upgrade $package` for each package in the output or something, based on a nightly CI job / cron script thing.)

Thoughts? This is just an ongoing idea, rather than something for a specific milestone.

**Comment by rye** [comment]
I like this idea. Here's why.

I'm becoming more and more aware after outages like the one we had today that introducing dependencies on 3rd party services is dangerous. See: [npm outage on 2018-09-01](https://status.npmjs.org/incidents/v22ffls5cd6h), but also smaller projects like Greenkeeper and Danger which in our experience we have found to work from time to time, when they feel like it.  Part of this stems from their free nature; we haven't signed an SLA, so there's no guarantee that those'll work forever. Fine.

I like self-contained things that we version-control ourselves, and that we run from our own CI boxes, and that use some of our credentials or something to interact with GitHub, and that **we control**, not someone else.  Whether this just stems from my own arrogant contempt for seemingly trivial but breaking issues such as "DNS misconfiguration," (especially when they affect large populations) I think it's a valid sentiment to keep in our minds as we evaluate the usefulness of the specific tool, Greenkeeper.

Because of its black-box and inconsistent nature, I am all for breaking up with Greenkeeper.

However:

- **I like Greenkeeper's style.** I like the fact that it is structured, and that it produces _predictable_, _straightforward_ pull requests.
- **I like Greenkeeper's automation.** I like the fact that, assuming someone hasn't pushed multiple versions in rapid sequence, you can click the merge button and be done.
- **I like Greenkeeper's visibility.** I want to be able to see _what the current version is_, _what the new version is_, and one of the cherries that Greenkeeper throws in is the GitHub "commits" listing. That's nice, but we don't really need it, but it's nice nonetheless.

Before we turn Greenkeeper off, we need to have something in place that has similar traits.

Bear in mind that, as we begin to send some our modules into their own homes, we will need to have a smart dependency manager that keeps things updated downstream.  I don't think Greenkeeper will be able to keep up with us, or us with Greenkeeper.

One of the things I'd like to explore is the possibility of having something that pushes to the same branch. It creates a branch whenever a new update is available for a given component, but that branch tracks new versions as they come down the wire.

Or, something that instead creates new PR's for each specific version and then updates old ones to close or something.

There's some words.

**Comment by hawkrives** [comment]
there's some words, indeed. thanks. I'll ponder them over the next $timeperiod.

**Comment by hawkrives** [comment]
I would really like to disable Greenkeeper on _this_ repository.

For me, it really boils down to this: I would rather go look for updates based on a pull model, rather than a push one.

That is, I would prefer to go check for updates when I am in the mood to find and integrate package updates, rather than have them show up in my GitHub notifications constantly.

We would, of course, want to look for updates before we do an app release, but I don't think that we need to be constantly upgrading packages.

/cc @rye, @drewvolz

**Comment by drewvolz** [comment]
Sounds reasonable.

**Comment by rye** [comment]
I like getting notifications, but only when it's a "review and merge" on my part.

I would much rather have these show up as issues, rather than not show up at all.

Since no such solution exists, a near-term choice would be to disable greenkeeper.

Also, since GitHub is doing dependency graphing for us, I don't think it's an issue.

Once we split this out into multiple modules, there'll hopefully be a lot less for us to manage—each module will get versioned independently and get its own dependency upgrades done… which will make this repository easier to use with Greenkeeper.

**Comment by hawkrives** [comment]
I have now disabled Greenkeeper on this repository.
