### ISSUE TITLE
Onesignal is out-of-date and has a few issues

### ISSUE THREAD

**Issue by drewvolz** [StoDevX/AAO-React-Native#3012]
1. Underlying iOS OneSignal library hasn't been updated for the past two patch versions (https://github.com/geektimecoil/react-native-onesignal/issues/616), so that may be part of our issue
2. There's a giant, easy to hit race condition around setting tags and they don't give us a way to know when a tag has been reset
    - Turn off or turn on a channel. 
    - Go home.
    - Reopen the app. See that the channel resets to the original state.
3. This is in addition to the bug where getTags sometimes just … never calls the callback

**Comment by Nightsd01** [comment]
Noticed a reference to this issue in one of the issues on our repo:

1. Just released 3.2.7 today to fix this. It also includes a new iOS SDK update that fixes a bunch of stuff.
2. I am not entirely sure what you mean here. Could you post an issue on our repo with some details as well?
3. A lot of apps/developers deeply misuse tags functionality in our SDK and call it _way_ too often, which would put a ton of stress on our servers. So we actually batch these requests when possible. Because of this, if you call `getTags` twice in a relatively short amount of time, the SDK will only maintain a reference to the most recent callback. We are considering storing an array of callbacks in a future release. But I would suggest making sure your app isn't calling `getTags` so frequently.

If you are referring to some other bug with `getTags` could you post an issue about that as well on our repo?

**Comment by hawkrives** [comment]
@Nightsd01 Hi! Thanks! We'll get ourselves updated soon.

Regarding our issues: sure, I'll write something up this week and post it.

Thanks again!

**Comment by hawkrives** [comment]
… Thinking about it more, and thinking through / playing with the app again, it seems like all we need to do is just _not call getTags on app resume_. (in the settings screen, which is the only place we were doing this.)

1. All we're trying to do on app resume is check the push status
2. The tag does get applied eventually (try toggling one on, going home, resuming about 10s later, then going home again, waiting about 60s; the toggle should be "on" after the second resume.),

**Comment by rye** [comment]
OneSignal upgrade PR: #3042, which is green.

**Comment by hawkrives** [comment]
Closed by #3042
