### ISSUE TITLE
circle: Ignore gh-pages

### ISSUE THREAD

**Issue by rye** [StoDevX/AAO-React-Native#3251]
It appears that our automated pushes to `gh-pages` are triggering builds, which freaks Circle out because they (_really_) want us to upgrade to 2.0.

![image](https://user-images.githubusercontent.com/1566689/49169980-b2cb0800-f300-11e8-8d37-73a91c55d3cc.png)

For workflows that apply to all branches currently, we could just add an `ignore`. Or maybe use a negative lookahead to ignore anything that includes `gh-pages`, if Circle's configuration syntax supports it?

Something along the lines of `/^(?!gh-pages).*$/` will take care of that.

**Comment by hawkrives** [comment]
I'll be honest – I don't know if we _can_ ignore `gh-pages`.

My understanding is that Circle subscribes to all `push` events; they then fetch the config file from the pushed branch (this is in contrast to Travis, who always uses `master`'s config).

So unless we put a config file on gh-pages, I don't think we can disable it.

---

I do want to note, though, that we can just _ignore_ this warning. We aren't using CircleCI 1.0, and we don't care what they do with the gh-pages branch. I expect that the warning will go away at some point in the future, anyway, as they continue to deprecate 1.0 further. It's only warning about 1.0 because of some _other_ legacy behavior, which is that a branch with no config defaults to the "auto-select and try to build" feature of CircleCI 1.0.

---

Thus, I think we should just ignore this warning.

**Comment by hawkrives** [comment]
Closing this as we're slowly moving away from Circle anyway.
