### ISSUE TITLE
Update screenshots and Xcode version

### ISSUE THREAD

**Issue by drewvolz** [StoDevX/AAO-React-Native#3591]
We need to start building AAO with iOS 12.1 SDK or later, and provide XS Max and iPad Pro 3rd gen screenshots

https://developer.apple.com/news/?id=03202019a

> Starting March 27, 2019, all new apps and app updates for iPhone or iPad, including universal apps, must be built with the iOS 12.1 SDK or later and support iPhone XS Max or the 12.9-inch iPad Pro (3rd generation). Screenshots for these devices will also be required.

- [x] update xcode (#3597)
- [ ] update screenshots

**Comment by hawkrives** [comment]
Given that the App Store won't let us submit the new build without the screenshots, I think we can close this (since we don't store the screenshots in the repo).

(ie i'm arguing that we won't forget to do the screenshots if we close the issue)

(plus it looks like we'll have some new things to take screenshots of anyway so)
