### ISSUE TITLE
Add dorm-specific dining hours info

### ISSUE THREAD

**Issue by willjad** [StoDevX/AAO-React-Native#4841]
Dining hours are posted to https://wp.stolaf.edu/reslife/dining-hours/ each day to inform students of when their dorm can get food. It would be nice of AAO could display this information in-app. I'm not sure where this information would be best displayed, but probably under the Stav Hall building hours? Alternatively, each housing location could have its own panel so a student could favorite their own for easy access.

**Comment by rye** [comment]
Thanks for the feedback and kicking off an issue here! I think this is definitely worth exploring, and I've spent this morning/afternoon hacking on a tool to build this for us, now proposed in #4843.

There are two ways to do this with our system, each with their own tradeoffs.

- Currently, spaces can have multiple schedules. For example, Stav (currently) has a "Breakfast", "Lunch", and "Dinner" schedule. If we add more schedules so that we have a breakfast, lunch, and dinner schedule for all the dorms, that'll let us keep them all grouped together under "Stav Hall". It'll get a little bit busy on the screen of people, but active schedules are bolded.

- Another way to do this would be to split Stav into 14 individual "spaces", but this would take up even more of the user's screen. The only benefit I could see there is that the user could favorite their dorm's thing, which would help reduce clutter.

In #4843 I have written a solution that goes with the former choice, creating an "Hoyme — Lunch", etc. schedule for each building-menu combination. I'll keep an eye on that page as it changes and see about automating the process of populating the Stav hours until something changes with how hours are put on that page.

**Comment by rye** [comment]
A brief update to keep #4843 in sync.

The appearance of the changes made there was… <details><summary>less than ideal</summary><img src="https://user-images.githubusercontent.com/1566689/90992616-906a2b00-e576-11ea-9848-5af095a32fa9.png"> (thanks @drewvolz for checking this before it was merged)</details>

So I pushed changes and we are now splitting each of the dorms into their own individual version of Stav, which looks quite a bit better (screenshot is out-of-date):

<details><summary>New appearance</summary><img src="https://user-images.githubusercontent.com/1566689/90993831-00c77b00-e57c-11ea-966a-cf887da9e9e9.png"></details>

This has some hidden benefits that I didn't think of:

- Users can favorite their dorm's copy. (…we already knew this)
- Each dorm's copy also has its own "open" vs "closed" status so that people can more easily tell when they can go, especially if they have their dorm favorited.

We should (hopefully) be able to get this deployed, at which point I'll be restarting our caching server so we can get the new data bundle out quickly.

**Comment by willjad** [comment]
NB we're now switching to individual sign-ups for each meal slot, so it may be good to wait on pushing those changes to app/play store. If things go well, we resume normal dining on September 3. Otherwise I think it'll be back to scheduling by dorm.

**Comment by hawkrives** [comment]
@willjad Do you see the changes I made last night/this morning, where I just marked Stav as being reservation-only?

**Comment by willjad** [comment]
Ah I do now. Just FYI, it seems to break the ability to see any other building hours info. 
![Screenshot_20200826-145621](https://user-images.githubusercontent.com/9014216/91350539-73b73880-e7ac-11ea-9f22-2c48cbeefd77.png)
Pixel 3 running latest Android public beta version
