### ISSUE TITLE
Cage menu only showing specials

### ISSUE THREAD

**Issue by drewvolz** [StoDevX/AAO-React-Native#520]
By default we list the "specials" first as to cut down on the amount of items we render. I am noticing that non-specials will not render on the cage menu, and the cage menu alone.

I made sure to check the JSON that was returned for specials -- they exist. We need to figure out why non-specials will not render.

**Comment by hawkrives** [comment]
Turns out that the Cage's menu is only _listing_ the specials, as well.

```json
[
  {"label": "Breakfast", "items": ["6391184"]},
  {"label": "Hot Sandwich Feature", "items": ["6391207"]},
  {"label": "Grab-n-Go Sandwich", "items": ["6391221", "6391243"]},
  {"label": "Grab-n-Go Salad", "items": ["6391254"]},
  {"label": "Burger of the Week", "items": ["6391263"]},
  {"label": "Chili of the Week", "items": ["6391278"]},
  {"label": "Vegetarian Chili of the Week", "items": ["6391293"]},
  {"label": "Cage House Soup", "items": ["6391312"]},
  {"label": "Wrap of the Week", "items": ["6391303"]}
]
```

You'll notice that each station only references one to two items, which lines up with what we see rendered in the menu:

<img width="320" alt="screen shot 2017-01-09 at 9 34 25 am" src="https://cloud.githubusercontent.com/assets/464441/21771888/d20564de-d64e-11e6-82eb-733af023a8d3.png">

So this is a data problem, and someone will need to email BonApp about it.

---

For contrast, here's the stations list for breakfast in the Caf:

```json
[
  {
    "label": "tortilla",
    "items": [
      "5291214",
      "5291215",
      "5291216"
    ]
  },
  {
    "label": "breakfast",
    "items": [
      "5297213",
      "5297214",
      "5297261",
      "5297262",
      "5297263",
      "5297264",
      "5297265"
    ]
  },
  {
    "label": "salad bar",
    "items": [
      "5317952",
      "5317953",
      "5317954",
      "5317955",
      "5317956",
      "5317958"
    ]
  }
]
```

**Comment by drewvolz** [comment]
Good investigation. Seems we have bad data.

**Comment by hawkrives** [comment]
@elijahverdoorn What do you think about talking to BonApp about putting more than just specials in their Cage menu?

**Comment by drewvolz** [comment]
I'll fill out a feedback form to bon app to ask about the Cage menu non-specials

**Comment by elijahverdoorn** [comment]
I can get some momentum going on this.

**Comment by hawkrives** [comment]
Thanks @elijahverdoorn!
