### ISSUE TITLE
Add app analytics?

### ISSUE THREAD

**Issue by hawkrives** [StoDevX/AAO-React-Native#528]
Building off of https://github.com/StoDevX/AAO-React-Native/issues/65#issuecomment-240283060, we should add an analytics library to the app, so we know what parts of the app people use.

Service ideas:
- Sentry.io
- Keen.io
- Google Analytics

Thoughts? Yea / nay?

(We should also make it opt-outable, since we're not in the EU and don't have to make it opt-in. Or we could be nice and show a little toast bar at the bottom the, like, second time you open the app or something.)

**edit 2017/1/9 3:30pm:** added keen.io

**Comment by drewvolz** [comment]
I am excited about this idea. I think Google Analytics would work well for our needs. We should brainstorm at some point _what_ we would be interested in tracking. Unique user count? Most used sections? Times when app is used? Most sought out student orgs, dictionary definitions, building hours? Most popular home-view order/layout?

**Update**: versions out in the wild? build numbers? crashes? localization statistics?

**Comment by elijahverdoorn** [comment]
I support Google Analytics, since that is the analytics solution we use for Oleville, so my team is already familiar with it. I think I'm most interested in the routes - From the home screen, what is the path the user takes through the app? I love graphs like this: 
![image](https://cloud.githubusercontent.com/assets/12042702/21833500/3407d28c-d778-11e6-9a30-468a2ba50d9f.png)

Other than that, I think we can use this data to support the removal or addition of features, as well as focus our development in the future.
