### ISSUE TITLE
Investigate platform specific build steps

### ISSUE THREAD

**Issue by drewvolz** [StoDevX/AAO-React-Native#6320]
We should look into whether our build steps that run / skip platform-specific code are configured correctly.

For #6319 (an Android `build.gradle` change)
- `iOS Cocoapods (push)` (running)
- `Build for Android` (skipped)

<img width="535" alt="Screen Shot 2022-08-17 at 10 28 45 PM" src="https://user-images.githubusercontent.com/5240843/185301789-f6ec7d4d-f8d5-4680-9ea3-a43e4f81d4ef.png">

**Comment by hawkrives** [comment]
This is correct (albeit confusing).

- `iOS Cocoapods` only depends on "cache npm macos" and "cache bundler macos", so it's still running.
- `Build for Android` and `Build for iOS` depend on "Bundle for $platform", "Jest", "tsc", "ESLint", and the various caching jobs

Because both tsc and ESLint failed, "build for Android" was skipped, and I'll bet that "build for iOS" was also already skipped at the time this screenshot was taken (albeit off the bottom of the 'shot).

**Comment by drewvolz** [comment]
Appreciate the analysis. Closing this!
