### ISSUE TITLE
Handle broken links

### ISSUE THREAD

**Issue by drewvolz** [StoDevX/AAO-React-Native#864]
An Oleville post located here http://oleville.com/blog/2017-spring-elections-voting-day/ contains a URL that crashes AAO. We should handle this situation.

`<a href="www.oleville.com/elections/vote">here</a>` lacks the protocol `http://` or `https://`

The error is:

```
ExceptionsManager.js:71 Exception 'The specified URL has an unsupported scheme.
Only HTTP and HTTPS URLs are supported.' was thrown while invoking show on 
target SafariViewManager with params (
        {
        url = "www.oleville.com/elections/vote";
    },
    97
)
```

**Comment by hawkrives** [comment]
So. Browsers (including WebView) handle links without a protocol by simply appending the link's href to the current location (so, on http://web.site if you click a link to http://stolaf.edu, you'll go to stolaf.edu; but if the link is just to stolaf.edu, you'd be going to http://web.site/stolaf.edu.)

That doesn't work for us... because we have no location for the news articles, since we're just loading HTML strings. 

So we will need to either figure out a way to set the location (unlikely; I don't think we can do that) or just check for a protocol on the opened link in the handler, and prepend the current article's source href to the link if there's no protocol.
