### ISSUE TITLE
Fix presence calendar sort order

### ISSUE THREAD

**Issue by drewvolz** [StoDevX/AAO-React-Native#866]
March 14th
March 31st
March 16th

<img src="https://cloud.githubusercontent.com/assets/5240843/23882026/7b8bb7f8-0834-11e7-8a29-89dc315a3fc8.jpg" height="400" />

**Comment by hawkrives** [comment]
Huh. 

I guess it's sorting by org, then date.

**Comment by hawkrives** [comment]
https://github.com/StoDevX/AAO-React-Native/blob/master/source/views/calendar/calendar-presence.js

See convertEvents. 

The question is, does Array#sort return `this` or `undefined`? If "this", then we can just chain the sort() call into the end after the filter(); otherwise, we'd need to change the function from purely returning to do a "const events =; events.sort(stuff); return events" sort of thing.

**Comment by drewvolz** [comment]
Chaining the `sort()` after does not do the trick.
